//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : AppClass.sm
//

#ifndef APPCLASS_SM_H
#define APPCLASS_SM_H


#define SMC_USES_IOSTREAMS

#include <statemap.h>

// Forward declarations.
class MainMap;
class MainMap_Start;
class MainMap_type_contact;
class MainMap_state_1;
class MainMap_state_2;
class MainMap_state_3;
class MainMap_state_4;
class MainMap_user_name;
class MainMap_server_name;
class MainMap_zone_name;
class MainMap_Error;
class MainMap_OK;
class MainMap_Default;
class AppClassState;
class AppClassContext;
class AppClass;

class AppClassState :
    public statemap::State
{
public:

    AppClassState(const char * const name, const int stateId)
    : statemap::State(name, stateId)
    {};

    virtual void Entry(AppClassContext&) {};
    virtual void Exit(AppClassContext&) {};

    virtual void EOS(AppClassContext& context);
    virtual void digit(AppClassContext& context, char dig);
    virtual void dog(AppClassContext& context, char dg);
    virtual void dot(AppClassContext& context, char dt);
    virtual void dots(AppClassContext& context, char dts);
    virtual void equal(AppClassContext& context, char equ);
    virtual void letter(AppClassContext& context, char let);
    virtual void question(AppClassContext& context, char quest);
    virtual void restart(AppClassContext& context);
    virtual void unknown(AppClassContext& context, char unk);

protected:

    virtual void Default(AppClassContext& context);
};

class MainMap
{
public:

    static MainMap_Start Start;
    static MainMap_type_contact type_contact;
    static MainMap_state_1 state_1;
    static MainMap_state_2 state_2;
    static MainMap_state_3 state_3;
    static MainMap_state_4 state_4;
    static MainMap_user_name user_name;
    static MainMap_server_name server_name;
    static MainMap_zone_name zone_name;
    static MainMap_Error Error;
    static MainMap_OK OK;
};

class MainMap_Default :
    public AppClassState
{
public:

    MainMap_Default(const char * const name, const int stateId)
    : AppClassState(name, stateId)
    {};

    virtual void restart(AppClassContext& context);
    virtual void letter(AppClassContext& context, char let);
    virtual void digit(AppClassContext& context, char dig);
    virtual void dots(AppClassContext& context, char dts);
    virtual void dot(AppClassContext& context, char dt);
    virtual void equal(AppClassContext& context, char equ);
    virtual void question(AppClassContext& context, char quest);
    virtual void dog(AppClassContext& context, char dg);
    virtual void EOS(AppClassContext& context);
    virtual void unknown(AppClassContext& context, char unk);
};

class MainMap_Start :
    public MainMap_Default
{
public:
    MainMap_Start(const char * const name, const int stateId)
    : MainMap_Default(name, stateId)
    {};

    virtual void dots(AppClassContext& context, char dts);
    virtual void letter(AppClassContext& context, char let);
};

class MainMap_type_contact :
    public MainMap_Default
{
public:
    MainMap_type_contact(const char * const name, const int stateId)
    : MainMap_Default(name, stateId)
    {};

    virtual void letter(AppClassContext& context, char let);
    virtual void question(AppClassContext& context, char quest);
};

class MainMap_state_1 :
    public MainMap_Default
{
public:
    MainMap_state_1(const char * const name, const int stateId)
    : MainMap_Default(name, stateId)
    {};

    virtual void letter(AppClassContext& context, char let);
};

class MainMap_state_2 :
    public MainMap_Default
{
public:
    MainMap_state_2(const char * const name, const int stateId)
    : MainMap_Default(name, stateId)
    {};

    virtual void letter(AppClassContext& context, char let);
};

class MainMap_state_3 :
    public MainMap_Default
{
public:
    MainMap_state_3(const char * const name, const int stateId)
    : MainMap_Default(name, stateId)
    {};

    virtual void letter(AppClassContext& context, char let);
};

class MainMap_state_4 :
    public MainMap_Default
{
public:
    MainMap_state_4(const char * const name, const int stateId)
    : MainMap_Default(name, stateId)
    {};

    virtual void equal(AppClassContext& context, char equ);
};

class MainMap_user_name :
    public MainMap_Default
{
public:
    MainMap_user_name(const char * const name, const int stateId)
    : MainMap_Default(name, stateId)
    {};

    virtual void digit(AppClassContext& context, char dig);
    virtual void dog(AppClassContext& context, char dg);
    virtual void letter(AppClassContext& context, char let);
};

class MainMap_server_name :
    public MainMap_Default
{
public:
    MainMap_server_name(const char * const name, const int stateId)
    : MainMap_Default(name, stateId)
    {};

    virtual void digit(AppClassContext& context, char dig);
    virtual void dot(AppClassContext& context, char dt);
    virtual void letter(AppClassContext& context, char let);
};

class MainMap_zone_name :
    public MainMap_Default
{
public:
    MainMap_zone_name(const char * const name, const int stateId)
    : MainMap_Default(name, stateId)
    {};

    virtual void EOS(AppClassContext& context);
    virtual void letter(AppClassContext& context, char let);
};

class MainMap_Error :
    public MainMap_Default
{
public:
    MainMap_Error(const char * const name, const int stateId)
    : MainMap_Default(name, stateId)
    {};

};

class MainMap_OK :
    public MainMap_Default
{
public:
    MainMap_OK(const char * const name, const int stateId)
    : MainMap_Default(name, stateId)
    {};

};

class AppClassContext :
    public statemap::FSMContext
{
public:

    explicit AppClassContext(AppClass& owner)
    : FSMContext(MainMap::Start),
      _owner(owner)
    {};

    AppClassContext(AppClass& owner, const statemap::State& state)
    : FSMContext(state),
      _owner(owner)
    {};

    virtual void enterStartState()
    {
        getState().Entry(*this);
        return;
    }

    inline AppClass& getOwner()
    {
        return (_owner);
    };

    inline AppClassState& getState()
    {
        if (_state == NULL)
        {
            throw statemap::StateUndefinedException();
        }

        return dynamic_cast<AppClassState&>(*_state);
    };

    inline void EOS()
    {
        setTransition("EOS");
        getState().EOS(*this);
        setTransition(NULL);
    };

    inline void digit(char dig)
    {
        setTransition("digit");
        getState().digit(*this, dig);
        setTransition(NULL);
    };

    inline void dog(char dg)
    {
        setTransition("dog");
        getState().dog(*this, dg);
        setTransition(NULL);
    };

    inline void dot(char dt)
    {
        setTransition("dot");
        getState().dot(*this, dt);
        setTransition(NULL);
    };

    inline void dots(char dts)
    {
        setTransition("dots");
        getState().dots(*this, dts);
        setTransition(NULL);
    };

    inline void equal(char equ)
    {
        setTransition("equal");
        getState().equal(*this, equ);
        setTransition(NULL);
    };

    inline void letter(char let)
    {
        setTransition("letter");
        getState().letter(*this, let);
        setTransition(NULL);
    };

    inline void question(char quest)
    {
        setTransition("question");
        getState().question(*this, quest);
        setTransition(NULL);
    };

    inline void restart()
    {
        setTransition("restart");
        getState().restart(*this);
        setTransition(NULL);
    };

    inline void unknown(char unk)
    {
        setTransition("unknown");
        getState().unknown(*this, unk);
        setTransition(NULL);
    };

private:
    AppClass& _owner;
};


#endif // APPCLASS_SM_H

//
// Local variables:
//  buffer-read-only: t
// End:
//
